import React from 'react'

function Footer() {
  return (
    <div className='text-center mt-20' style={{ color: 'var(--text-primary)' }}>
      <h2>Created By Fravel || AI-TRIP_PLANNER </h2>
      <h2>© {new Date().getFullYear()} All rights are reserved by Fravel - the AI trip planner</h2>
      <p className='text-xs' style={{ color: 'var(--text-muted)' }}>Note : Results and Images  generated by AI may include inaccuracies . Cross-check before making decisions.</p>
    </div>
  )
}

export default Footer
